name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # If your v0 zip uses pnpm, this will install with pnpm; else fallback to npm.
      - name: Install dependencies (pnpm or npm)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            corepack prepare pnpm@8 --activate
            pnpm install --frozen-lockfile=false
          else
            npm config set legacy-peer-deps true
            npm install --legacy-peer-deps
          fi

      # Build your site. For Next 13+ static export, next.config.js should have:  output: 'export'
      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          GITHUB_PAGES: "true"
        run: |
          if npm run | grep -qE '(^| )gh:build( |$)'; then
            npm run gh:build || npm run build
          else
            npm run build
          fi

      # Verify 'out' exists (friendly error if not)
      - name: Verify export folder
        run: |
          if [ ! -d out ]; then
            echo "::error::Expected ./out folder not found. Ensure next.config.js has: module.exports = { output: 'export' }"
            ls -la
            exit 1
          fi

      - name: Upload artifact (out)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
